### ISSUE TITLE
Request to Elasticsearch failed: {"error":{}}

### ISSUE THREAD

**Issue by FFrozTT** [creekorful/trandoshan#13]
So I've had all containers running overnight without exiting and there is certainly a lot of activity but something doesn't seem quite right between Kibana and Elasticsearch. Kibana is only showing me 8 entry's and giving this error:

```
Request to Elasticsearch failed: {"error":{}}

Error: Request to Elasticsearch failed: {"error":{}}
    at http://x.x.x.x:15004/bundles/commons.bundle.js:3:4900279
    at Function._module.service.Promise.try (http://x.x.x.x:15004/bundles/commons.bundle.js:3:2504083)
    at http://x.x.x.x:15004/bundles/commons.bundle.js:3:2503457
    at Array.map (<anonymous>)
    at Function._module.service.Promise.map (http://x.x.x.x:15004/bundles/commons.bundle.js:3:2503414)
    at callResponseHandlers (http://x.x.x.x:15004/bundles/commons.bundle.js:3:4898793)
    at http://x.x.x.x:15004/bundles/commons.bundle.js:3:4881154
    at processQueue (http://x.x.x.x:15004/built_assets/dlls/vendors.bundle.dll.js:435:204190)
    at http://x.x.x.x:15004/built_assets/dlls/vendors.bundle.dll.js:435:205154
    at Scope.$digest (http://x.x.x.x:15004/built_assets/dlls/vendors.bundle.dll.js:435:215159)
```

**Comment by creekorful** [comment]
I confirm the issue.

I have restarted the crawler and it worked. But it's not really a fix.
I'll take a look! Thank you

**Comment by FFrozTT** [comment]
I'm cautiously optimistic but it appears to be working now...

Sweet!

**Comment by creekorful** [comment]
> I'm cautiously optimistic but it appears to be working now...
> 
> Sweet!

Have you done something special? Restarted the containers?
